version: '3.9'

services:
  users-db:
    image: postgres:13.4-alpine
    restart: always
    container_name: user-db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
